apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-server
  namespace: cloud
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-server
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50